# Generated by Django 5.1.2 on 2024-11-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='address',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='phone',
        ),
    ]
